config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy,:show]
  resources :users, only: [:new, :create, :destroy,:show]
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 255 }
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # ここから追記
  before_action :authenticate_user
  before_action :set_post, only: [:show,:edit,:update,:destroy]
  before_action :ensure_correct_user, only:[:edit,:destroy]

  def index
    @posts = Post.all
  end
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, notice: "投稿を作成しました"
      else
        render :new
      end
    end
  end

  def edit
  end
  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "投稿を編集しました！"
    else
      render :edit
    end
  end
  def show
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "投稿を削除しました"
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

  private
  def post_params
    params.require(:post).permit(:title, :content,:image, :image_cache)
  end
  def set_post
    @post = Post.find(params[:id])
  end

  def authenticate_user
    unless logged_in?
      redirect_to new_session_path
    end
  end
  def ensure_correct_user
    unless current_user.id == @post.user_id #IDと比較する。ユーザーIDと比較する

      redirect_to posts_path, notice: "あなたが投稿したもの以外は編集、削除できません。"
    end
  end
 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                               :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div class="container-fluid">
  <head>
    <title>フェイスブッククローン</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">  <!-- head内にこのタグ設定を追記する -->
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head>
  <header>
    <div class = "text-right header_text">
      <% if logged_in? %>
      <span class="fa fa-facebook-square"</span>
      <%= "#{current_user.name}" %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <% else %>
      <%= "あなたは今ログインしていません" %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
      <% end %>
      <a ><i class="fa fa-home fa-fw"></i>&nbsp; Home</a>
      <a><i class="fa fa-book fa-fw"></i>&nbsp; Library</a>
      <a ><i class="fa fa-pencil fa-fw"></i>&nbsp; Applications</a>
      <a><i class="fa fa-cog fa-fw"></i>&nbsp; Settings</a>
    </div>
  </header>
  <body>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
    <footer>
      <p>フェイスブッククローン</p>
      <p>© 2020 5/20 ~ 5/25 ５月期小野作成</p>
    </footer>
  </body>
</div>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true,url: choose_new_or_edit) do |form| %>
<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= @post.errors.count %>件のエラーがあります。</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div id = "form">
  <div class="row">
    <div class="col-md-2 col-md-offset-6">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <br>
    <div class="col-md-2 col-md-offset-6">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <br>
    <div class="col-md-2 col-md-offset-6">
      <%= form.label :image %>
      <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>
    <br>
    <div class="col-md-6 col-md-offset-6">
      <%= form.submit value = "投稿するする〜"%>
    </div>
    <br>
  </div>
</div>
<% end %>
<button type="button" class="btn btn-default col-md-2 col-md-offset-6">
  <%= link_to "投稿一覧画面にもどる", posts_path %>
</button>

app/views/posts/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>
  <p>タイトル:<%= @post.title %></p>
  <p>本文:<%= @post.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/posts/edit.html.erb
<h2 class = "text-center">投稿を編集する</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<h2>投稿一覧</h2>
<table>
  <tr>
    <th>
      タイトル
    </th>
    <th>投稿内容</th>
  </tr>
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
      <td type="button" class="btn btn-info"><%= link_to '詳細を確認する', post_path(post.id) %></td>
      <td type="button" class="btn btn-default"><%= link_to "投稿を編集する", edit_post_path(post.id), data: { confirm: '本当に編集していいですか？' } %></td>
      <td type="button" class="btn btn-danger"><%= link_to '投稿を削除する', post_path(post.id),data: { confirm: '本当に削除していいですか？' }, method: :delete %></td>
  </tr>
<% end %>
</table>
<button type="button" class = "btn btn-default">
<%= link_to '新しく投稿する', new_post_path %>
</button>

app/views/posts/new.html.erb
<h2>投稿を作成する</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h2>投稿詳細画面</h2>
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Image:</strong>
    <%= image_tag @post.image.url %>
  </p>
  <p>内容: <%= @post.content %></p>
  <%= link_to '新しく投稿する', new_post_path %>
<%# この行に編集画面へのリンクを追加する必要がある？ %>
  <br>
  <%= link_to '投稿一覧', posts_path %>

app/views/users/new.html.erb
<h2 class ="text-center">Sign up</h2>
<% if @user.errors.any? %>
<!--error_explanationをIDに設定するとデフォルトで設定されているスタイルが適用される -->
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class = "text-center">
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "アカウントを作成する" %>
<% end %>
</div>

app/views/users/show.html.erb
<h2>ユーザー詳細画面</h2>
  <p id="notice"><%= notice %></p>
  <h2><%= @user.name %>のページ</h2>
  <p>メールアドレス: <%= @user.email %></p>
  <% @user.posts.each do |post| %>
    <tr >
      <td id="user_tr_color">タイトル:<%= post.title %></td>
      <td>投稿内容:<%= post.content %></td>
      <td><%= link_to '詳細を確認する', post_path(post.id) %></td>
      <td><%= link_to "投稿を編集する", edit_post_path(post.id), data: { confirm: '本当に編集していいですか？' } %></td>
      <td><%= link_to '投稿を削除する', post_path(post.id),data: { confirm: '本当に削除していいですか？' }, method: :delete %></td>
      <td><%= link_to '新しく投稿する', new_post_path %> <td>
      <td><%= link_to 'みんなの投稿', posts_path %> </td
    </tr>
  <% end %>

  <%= link_to '新しく投稿する', new_post_path %>
  <%= link_to 'みんなの投稿', posts_path %>